import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "@/theme/ThemeRegistry";
import Providers from "./providers";
import {ReactNode} from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      {" "}
      <ThemeRegistry>
        {" "}
        <body suppressHydrationWarning={true}>
          <Providers>{children}</Providers>
        </body>
      </ThemeRegistry>
    </html>
  );
}
